require 'spree'
require 'spree_api_v1'
require 'spree_backend'
require 'spree_auth_devise'
require 'spree_multi_vendor'
require 'spree_reviews'
require 'spree_extension'
require 'spree_cm_commissioner/engine'
require 'spree_cm_commissioner/version'
require 'spree_cm_commissioner/passenger_option'
require 'spree_cm_commissioner/payment_method_group'
require 'spree_cm_commissioner/calendar_event'
require 'spree_cm_commissioner/s3_url_generator'

require 'google/cloud/recaptcha_enterprise'
require 'searchkick'
require 'twilio-ruby'
require 'elasticsearch'
require 'interactor'
require 'phonelib'
require 'jwt'
require 'noticed'
require 'aws-sdk-s3'
require 'telegram/bot'
require 'exception_notification'

require 'simple_calendar'
require 'activerecord_json_validator'
require 'googleauth'
require 'dry-validation'
require 'font-awesome-sass'
require 'rqrcode'
require 'premailer/rails'

require 'byebug' if Rails.env.development? || Rails.env.test?
