# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-ruby
name: Commissioner Gem

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - develop
      - milestone-77-scalable-design
  push:
    tags:
      - "*"
jobs:
  test_and_build_gem:
    # if: github.head_ref != '2572-enforce-pr-workflow' || github.base_ref != 'develop'
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: test_db

        ports: ["5432:5432"]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379 # Maps port 6379 on service container to the host

    steps:
      - uses: actions/checkout@v3

      # - uses: borales/actions-yarn@v2.0.0
      #   with:
      #     cmd: install

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.0"

          # bundle-cache might cause problem when upgrading ruby. Disable it when upgrading to solve the problem.
          # bundler-cache: true

      - name: Install dependencies
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install --jobs 4 --retry 3

      # Build the gem
      - name: Build gem
        env:
          DATABASE_URL: postgres://myuser:mypassword@localhost:5432/test_db

        # if: startsWith(github.ref, 'refs/tags/') # Only on tag pushes
        if: |
          startsWith(github.ref, 'refs/tags/')
        run: |
          gem build *.gemspec

      # Publish the gem
      - name: Publish gem
        env:
          DATABASE_URL: postgres://myuser:mypassword@localhost:5432/test_db

        # if: startsWith(github.ref, 'refs/tags/') # Only on tag pushes
        # (github.event_name == 'push' && github.ref == 'refs/heads/2405-build-and-publish-gem')
        if: |
          startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p ~/.gem
          echo ":rubygems_api_key: ${{ secrets.RUBYGEMS_API_KEY }}" > ~/.gem/credentials
          chmod 0600 ~/.gem/credentials
          gem push *.gem
